### ISSUE TITLE
Aircraft should randomly spawn with one of the predefined altitudes

### ISSUE THREAD

**Issue by CremboC** [CremboC/INI#57]
Make it so an aircraft spawn with one of the predefined altitudes.
I recommending storing the altitudes in the Config files, best way to make an array is:
`public static final int[] ALTITUDES = {1, 2, 3}`
Then you can access it simply using ALTITUDES[0] etc.

**Comment by LeslieHor** [comment]
Whoops. Forgot to add the #57 in my comment. But I did this the way you said.
